version: 1
updated_at: "2026-06-02T17:18:54Z"
entries:
    cloudflare.com:
        sni: cloudflare.com
        description: Live-captured 2026-06-02
        settings_snapshot:
            ENABLE_PUSH: 0
            HEADER_TABLE_SIZE: 4096
            INITIAL_WINDOW_SIZE: 65536
            MAX_CONCURRENT_STREAMS: 100
            MAX_FRAME_SIZE: 16777215
    g.alicdn.com:
        sni: g.alicdn.com
        description: Live-captured 2026-06-02
        settings_snapshot:
            ENABLE_PUSH: 0
            HEADER_TABLE_SIZE: 4096
            INITIAL_WINDOW_SIZE: 65536
            MAX_CONCURRENT_STREAMS: 128
            MAX_FRAME_SIZE: 16777215
    www.apple.com:
        sni: www.apple.com
        description: Live-captured 2026-06-02
        settings_snapshot:
            ENABLE_PUSH: 0
            HEADER_TABLE_SIZE: 4096
            INITIAL_WINDOW_SIZE: 65535
            MAX_CONCURRENT_STREAMS: 100
            MAX_FRAME_SIZE: 16384
            MAX_HEADER_LIST_SIZE: 32768
    www.google.com:
        sni: www.google.com
        description: Live-captured 2026-06-02
        settings_snapshot:
            ENABLE_PUSH: 0
            HEADER_TABLE_SIZE: 4096
            INITIAL_WINDOW_SIZE: 1048576
            MAX_CONCURRENT_STREAMS: 100
            MAX_FRAME_SIZE: 16384
            MAX_HEADER_LIST_SIZE: 65536
    www.microsoft.com:
        sni: www.microsoft.com
        description: Live-captured 2026-06-02
        settings_snapshot:
            ENABLE_PUSH: 0
            HEADER_TABLE_SIZE: 4096
            INITIAL_WINDOW_SIZE: 65535
            MAX_CONCURRENT_STREAMS: 100
            MAX_FRAME_SIZE: 16384
            MAX_HEADER_LIST_SIZE: 32768
